In [1]:
#For Apex AD2600 Progressive-scan DVD player

In [2]:
#Step1: Extracting all adjectives from the given dataset

In [3]:
import nltk

#we may have to download stopwords first before importing it. to do which we can use
#nltk.download('stopwords')

import pandas as pd

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize, sent_tokenize
from collections import Counter

In [4]:
dataset=pd.read_csv('D:/4th sem/Research project/implementing hybrid approach/corpus for implicit aspect indicator extraction/v1/Apex AD2600 Progressive-scan DVD player.csv')
X=dataset.iloc[:,0].values
y=dataset.iloc[:,1].values

In [5]:
print(X)

['it practically plays almost everything you give it  '
 'i ve had the player for about 2 years now and it still performs nicely with the exception of an occasional wwhhhrrr sound from the motor  '
 'it s very sleek looking with a very good front panel button layout  and it has a great feature set  '
 'i have a dvd burner on my computer and a zillion mp3s  and it s a lot nicer to access them 45 gb at a time  dvdr  than 07 gb at a time  cdr   '
 'at doublespeed  2x forward speed   it still plays mp3s with sound  they are pitchcorrected and smooth  but twice as fast  '
 'there are funny little ridges on the dvd that look like the slice of a tree trunk  '
 'have used it frequently and have had no problems  '
 'they play just about everything  but  2 and  3 died very shortly after getting them  '
 'this item broke just two weeks after i gave it to my kids for christmas  '
 'it looks great  and is loaded with features  '
 'unfortunately it turns out to be the  disposable  type  '
 'the only

In [6]:
print(y)

['performance' 'performance' 'appearance' 'functionality' 'performance'
 'appearance' 'quality' 'performance' 'quality' 'appearance' 'quality'
 'performance' 'functionality' 'performance' 'functionality'
 'functionality' 'performance' 'performance' 'performance' 'quality'
 'quality' 'quality' 'performance' 'performance' 'quality' 'performance'
 'functionality' 'functionality' 'quality' 'quality' 'performance'
 'functionality' 'performance' 'performance' 'performance'
 'functionality ' 'performance' 'functionality' 'quality' 'performance'
 'quality' 'quality' 'functionality' 'behavior' 'performance' 'quality'
 'quality' 'quality' 'performance' 'performance' 'quality' 'size'
 'appearance' 'quality' 'quality' 'performance' 'functionality' 'quality'
 'quality' 'performance' 'performance' 'behavior' 'performance'
 'performance ' 'performance' 'price' 'quality' 'appearance' 'quality '
 'quality' 'functionality' 'performance' 'size' 'appearance' 'performance'
 'quality' 'functionality' 'funct

In [7]:
# Iterating through each word in the list y and removing the trailing spaces from each word
for i in range(len(y)):
    # Remove trailing spaces from the word
    y[i] = y[i].rstrip()

# Print the updated array of words
print(y)

['performance' 'performance' 'appearance' 'functionality' 'performance'
 'appearance' 'quality' 'performance' 'quality' 'appearance' 'quality'
 'performance' 'functionality' 'performance' 'functionality'
 'functionality' 'performance' 'performance' 'performance' 'quality'
 'quality' 'quality' 'performance' 'performance' 'quality' 'performance'
 'functionality' 'functionality' 'quality' 'quality' 'performance'
 'functionality' 'performance' 'performance' 'performance' 'functionality'
 'performance' 'functionality' 'quality' 'performance' 'quality' 'quality'
 'functionality' 'behavior' 'performance' 'quality' 'quality' 'quality'
 'performance' 'performance' 'quality' 'size' 'appearance' 'quality'
 'quality' 'performance' 'functionality' 'quality' 'quality' 'performance'
 'performance' 'behavior' 'performance' 'performance' 'performance'
 'price' 'quality' 'appearance' 'quality' 'quality' 'functionality'
 'performance' 'size' 'appearance' 'performance' 'quality' 'functionality'
 'function

In [8]:
#lets convert X into list
X_list=list(X)

In [11]:
#Also lets convert y into list
y_list=list(y)

In [9]:
print(X_list)

['it practically plays almost everything you give it  ', 'i ve had the player for about 2 years now and it still performs nicely with the exception of an occasional wwhhhrrr sound from the motor  ', 'it s very sleek looking with a very good front panel button layout  and it has a great feature set  ', 'i have a dvd burner on my computer and a zillion mp3s  and it s a lot nicer to access them 45 gb at a time  dvdr  than 07 gb at a time  cdr   ', 'at doublespeed  2x forward speed   it still plays mp3s with sound  they are pitchcorrected and smooth  but twice as fast  ', 'there are funny little ridges on the dvd that look like the slice of a tree trunk  ', 'have used it frequently and have had no problems  ', 'they play just about everything  but  2 and  3 died very shortly after getting them  ', 'this item broke just two weeks after i gave it to my kids for christmas  ', 'it looks great  and is loaded with features  ', 'unfortunately it turns out to be the  disposable  type  ', 'the only

In [12]:
print(y_list)

['performance', 'performance', 'appearance', 'functionality', 'performance', 'appearance', 'quality', 'performance', 'quality', 'appearance', 'quality', 'performance', 'functionality', 'performance', 'functionality', 'functionality', 'performance', 'performance', 'performance', 'quality', 'quality', 'quality', 'performance', 'performance', 'quality', 'performance', 'functionality', 'functionality', 'quality', 'quality', 'performance', 'functionality', 'performance', 'performance', 'performance', 'functionality', 'performance', 'functionality', 'quality', 'performance', 'quality', 'quality', 'functionality', 'behavior', 'performance', 'quality', 'quality', 'quality', 'performance', 'performance', 'quality', 'size', 'appearance', 'quality', 'quality', 'performance', 'functionality', 'quality', 'quality', 'performance', 'performance', 'behavior', 'performance', 'performance', 'performance', 'price', 'quality', 'appearance', 'quality', 'quality', 'functionality', 'performance', 'size', 'ap

In [13]:
len(y_list)

163

In [14]:
# Removing punctuation marks from each sentence in the list

import string

clean_sentences = [''.join(char for char in sentence if char not in string.punctuation) for sentence in X]

# print the clean sentences
print(clean_sentences)       

['it practically plays almost everything you give it  ', 'i ve had the player for about 2 years now and it still performs nicely with the exception of an occasional wwhhhrrr sound from the motor  ', 'it s very sleek looking with a very good front panel button layout  and it has a great feature set  ', 'i have a dvd burner on my computer and a zillion mp3s  and it s a lot nicer to access them 45 gb at a time  dvdr  than 07 gb at a time  cdr   ', 'at doublespeed  2x forward speed   it still plays mp3s with sound  they are pitchcorrected and smooth  but twice as fast  ', 'there are funny little ridges on the dvd that look like the slice of a tree trunk  ', 'have used it frequently and have had no problems  ', 'they play just about everything  but  2 and  3 died very shortly after getting them  ', 'this item broke just two weeks after i gave it to my kids for christmas  ', 'it looks great  and is loaded with features  ', 'unfortunately it turns out to be the  disposable  type  ', 'the only

In [15]:
# Create an empty list to store all the words of the corpus from the sentences(review) column
corpus_words = []

# loop over each sentence in the list
for sentence in clean_sentences:
    # split the sentence into words
    sentence_words = sentence.split()
    # loop over each word in the sentence
    for word in sentence_words:
        # append the word to the list
        corpus_words.append(word.lower())    #appending the lower case of the word

# print the list of words
print(corpus_words)

['it', 'practically', 'plays', 'almost', 'everything', 'you', 'give', 'it', 'i', 've', 'had', 'the', 'player', 'for', 'about', '2', 'years', 'now', 'and', 'it', 'still', 'performs', 'nicely', 'with', 'the', 'exception', 'of', 'an', 'occasional', 'wwhhhrrr', 'sound', 'from', 'the', 'motor', 'it', 's', 'very', 'sleek', 'looking', 'with', 'a', 'very', 'good', 'front', 'panel', 'button', 'layout', 'and', 'it', 'has', 'a', 'great', 'feature', 'set', 'i', 'have', 'a', 'dvd', 'burner', 'on', 'my', 'computer', 'and', 'a', 'zillion', 'mp3s', 'and', 'it', 's', 'a', 'lot', 'nicer', 'to', 'access', 'them', '45', 'gb', 'at', 'a', 'time', 'dvdr', 'than', '07', 'gb', 'at', 'a', 'time', 'cdr', 'at', 'doublespeed', '2x', 'forward', 'speed', 'it', 'still', 'plays', 'mp3s', 'with', 'sound', 'they', 'are', 'pitchcorrected', 'and', 'smooth', 'but', 'twice', 'as', 'fast', 'there', 'are', 'funny', 'little', 'ridges', 'on', 'the', 'dvd', 'that', 'look', 'like', 'the', 'slice', 'of', 'a', 'tree', 'trunk', 'hav

In [16]:
len(corpus_words)

2696

In [17]:
#Now we will remove all the stop words and apply lemmatization on corpus_words
# Loading the NLTK stopwords and lemmatizer

stop_words = set(stopwords.words('english'))  #set() function is then used to convert the list of stop words into a set

lemmatizer = WordNetLemmatizer()              #creating lemmatizer object   

In [18]:
#Removing stopwords and non-alphabetic characters from corpus_words
words = [word for word in corpus_words if word.isalpha() and word not in stop_words]

# Lemmatize the words
new_corpus_words = [lemmatizer.lemmatize(word) for word in words]    #converting all the tokenized words into their root form
    

In [19]:
print(new_corpus_words)

['practically', 'play', 'almost', 'everything', 'give', 'player', 'year', 'still', 'performs', 'nicely', 'exception', 'occasional', 'wwhhhrrr', 'sound', 'motor', 'sleek', 'looking', 'good', 'front', 'panel', 'button', 'layout', 'great', 'feature', 'set', 'dvd', 'burner', 'computer', 'zillion', 'lot', 'nicer', 'access', 'gb', 'time', 'dvdr', 'gb', 'time', 'cdr', 'doublespeed', 'forward', 'speed', 'still', 'play', 'sound', 'pitchcorrected', 'smooth', 'twice', 'fast', 'funny', 'little', 'ridge', 'dvd', 'look', 'like', 'slice', 'tree', 'trunk', 'used', 'frequently', 'problem', 'play', 'everything', 'died', 'shortly', 'getting', 'item', 'broke', 'two', 'week', 'gave', 'kid', 'christmas', 'look', 'great', 'loaded', 'feature', 'unfortunately', 'turn', 'disposable', 'type', 'thing', 'experience', 'problem', 'player', 'freezing', 'playing', 'able', 'clear', 'opening', 'blowing', 'canned', 'air', 'two', 'main', 'reason', 'getting', 'model', 'range', 'disk', 'type', 'played', 'recommendation', 'f

In [20]:
#Now our new_corpus_words contains words which are not stop words and in lemmatized form

In [21]:
#Extracting all the adjectives from the corpus_words
    
# Tag the words with their part of speech
tagged_words = nltk.pos_tag(new_corpus_words)

# Extract the adjectives from the tagged words
corpus_adjectives = [word for word, pos in tagged_words if pos.startswith('JJ')]

In [22]:
print(corpus_adjectives)

['nicely', 'occasional', 'sleek', 'good', 'great', 'nicer', 'gb', 'pitchcorrected', 'smooth', 'funny', 'little', 'dvd', 'christmas', 'great', 'loaded', 'disposable', 'type', 'able', 'clear', 'main', 'big', 'visual', 'literature', 'regular', 'disc', 'present', 'february', 'several', 'different', 'broken', 'tried', 'great', 'couple', 'new', 'disc', 'used', 'entire', 'raw', 'dvd', 'uk', 'progressive', 'scan', 'cool', 'different', 'wma', 'kodak', 'disc', 'great', 'surprised', 'stack', 'able', 'smart', 'stack', 'able', 'smart', 'worth', 'drawer', 'speak', 'longterm', 'little', 'big', 'silent', 'disk', 'le', 'wrong', 'apex', 'certain', 'old', 'rental', 'old', 'sharp', 'last', 'mirrorlike', 'front', 'sure', 'cool', 'mirrorlike', 'front', 'sure', 'cool', 'bad', 'find', 'remotecontrol', 'flimsy', 'eventualy', 'poor', 'manual', 'negative', 'dvd', 'disc', 'read', 'fine', 'loud', 'read', 'fine', 'loud', 'vbr', 'old', 'several', 'several', 'disc', 'several', 'several', 'disc', 'crappy', 'remote', '

In [23]:
print(len(corpus_adjectives))

267


In [24]:
#Now selecting only unique adjectives from the list of corpus_adjectives
corpus_adjectives_unique=list(set(corpus_adjectives))

In [25]:
print(corpus_adjectives_unique)

['act', 'cheasy', 'small', 'raw', 'compact', 'quality', 'multitude', 'visual', 'loud', 'real', 'tried', 'old', 'sharp', 'christmas', 'older', 'noiseless', 'quick', 'flimsy', 'negative', 'installed', 'present', 'regular', 'silent', 'video', 'remote', 'certain', 'great', 'worse', 'file', 'front', 'progressive', 'attractive', 'disposable', 'claim', 'oppressed', 'couple', 'uk', 'longterm', 'bang', 'wma', 'smooth', 'many', 'dvd', 'crappy', 'inexpensive', 'allow', 'poor', 'tv', 'several', 'audio', 'backup', 'attempted', 'froze', 'cheep', 'wide', 'affordable', 'broken', 'whole', 'kodak', 'main', 'disk', 'rental', 'fit', 'portable', 'slim', 'best', 'light', 'smart', 'scan', 'occasional', 'surprised', 'mirrorlike', 'expensive', 'drawer', 'looked', 'pirate', 'disc', 'played', 'cool', 'play', 'stable', 'least', 'first', 'nicely', 'good', 'find', 'recent', 'ok', 'install', 'nt', 'sleek', 'stack', 'nemo', 'february', 'original', 'big', 'entire', 'le', 'literature', 'little', 'bunch', 'clear', 'pitc

In [26]:
len(corpus_adjectives_unique)

152

In [27]:
#Step 2: Generating a Word2Vec frequency vector for each adjective that we have extracted

In [28]:
#downloading the pre-trained models and corpora from the Gensim data repository. 

import gensim.downloader

# Show all available models in gensim-data
print(list(gensim.downloader.info()['models'].keys()))

['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis']


In [30]:
# Download the "glove-twitter-25" embeddings
glove_vectors = gensim.downloader.load('glove-twitter-25')

In [31]:
len(glove_vectors)

1193514

In [32]:
#Use the downloaded vectors as usual:
glove_vectors.most_similar('played')

[('plays', 0.9272218942642212),
 ('lost', 0.9054622650146484),
 ('playing', 0.8980489373207092),
 ('won', 0.8965869545936584),
 ('pitch', 0.8960465788841248),
 ('since', 0.8898351192474365),
 ('beat', 0.8880069851875305),
 ('watched', 0.8869189620018005),
 ('had', 0.8818455338478088),
 ('seen', 0.8733781576156616)]

In [34]:
adj_similar_words_dict={}  #creating a dictonary to store adjectives and its related words taken from Word2Vec

for adj in corpus_adjectives_unique:
    if adj in glove_vectors:
        adj_similar_words=glove_vectors.most_similar(adj)
        #selecting only words from the tuple of words and similarity scores
        adj_words_only = [word for word, score in adj_similar_words]
        #print(adj_words_only)
        adj_similar_words_dict.update({adj:adj_words_only})

In [35]:
print(adj_similar_words_dict)

{'act': ['talk', 'not', 'understand', 'lie', 'people', 'stand', 'honest', 'person', 'ppl', 'speak'], 'small': ['side', 'your', 'own', 'more', 'their', 'clean', 'looking', 'find', 'bigger', 'or'], 'raw': ['classic', 'magic', 'epic', 'wild', 'wing', 'bowl', 'horse', 'spanish', 'ultimate', 'dutch'], 'compact': ['pvc', 'analog', 'magenta', 'laser', 'infrared', 'inch', 'aluminum', 'lens', 'tripod', 'optical'], 'quality': ['product', 'brand', 'selection', 'professional', 'limited', 'value', 'includes', 'standard', 'skills', 'creative'], 'multitude': ['likeness', 'disciplines', 'earthly', 'figment', 'untold', 'multitudes', 'motives', 'transgression', 'shyness', 'limitation'], 'visual': ['vocal', 'digital', 'marketing', 'creative', 'branding', 'storytelling', 'photoshop', 'master', 'html', 'audio'], 'loud': ['scared', 'crazy', 'scary', 'lonely', 'sound', 'drunk', 'turn', 'blowing', 'noise', 'mess'], 'real': ['play', 'big', 'young', 'one', 'stand', 'bad', 'crazy', 'better', 'than', 'beat'], 'tr

In [36]:
# Define a function to generate the Word2Vec similar words frequency vector for an adjective
Vri=[]   #Vri is going to store the frequencies of all words related to each adjective in a sublist
all_wordnets=[]    #creating a list of all wordnets from which we will select the list of unique wordnets which we will require in step 5
adj_wordnets_dict={} #creating dictionary to store all unique adjectives along with their related wordnets
def generate_frequency_vector(adj):
    freq_synsets=[]
    adj_wordnets=[]  #required for step 5
    if adj in glove_vectors:
        synsets = glove_vectors.most_similar(adj) # Get all synsets for an adjective and store it in synsets list
        synsets = [word for word, score in synsets]
        print(synsets)
        #lemmatizing the synsets
        synsets = [lemmatizer.lemmatize(word) for word in synsets]
        for synset in synsets:
        #synset_word=synset[0]  #extracting only the word from the tuple containing word and some number
            if synset!=adj:
                all_wordnets.append(synset)
                adj_wordnets.append(synset)  #required for step 5
                freq_word=new_corpus_words.count(synset)         #couting the frequency of synset word in all words that are in corpus
                freq_synsets.append(freq_word)
    
    Vri.append(freq_synsets)
    
    #selecting only unique wordnets from the list of adj_wordnets for an adjective (required for step 5)
    adj_wordnets_unique=list(set(adj_wordnets))
    
            
    #appending the dictionary adj_wordnets_dict with adj and its corresponding wordnet values (required for step 5)
    adj_wordnets_dict.update({adj:adj_wordnets_unique})
    
    return freq_synsets

In [37]:
# Generate Word2Vec related words frequency vectors for each adjective and store it a dictionary
adj_wordnet_freq_dict={}
for adj in corpus_adjectives_unique:
    freq_vector = generate_frequency_vector(adj)
    adj_wordnet_freq_dict.update({adj:freq_vector})
    print(adj, freq_vector)

['talk', 'not', 'understand', 'lie', 'people', 'stand', 'honest', 'person', 'ppl', 'speak']
act [0, 0, 1, 0, 0, 4, 0, 0, 0, 1]
cheasy []
['side', 'your', 'own', 'more', 'their', 'clean', 'looking', 'find', 'bigger', 'or']
small [0, 0, 0, 0, 0, 2, 2, 3, 0, 0]
['classic', 'magic', 'epic', 'wild', 'wing', 'bowl', 'horse', 'spanish', 'ultimate', 'dutch']
raw [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['pvc', 'analog', 'magenta', 'laser', 'infrared', 'inch', 'aluminum', 'lens', 'tripod', 'optical']
compact [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['product', 'brand', 'selection', 'professional', 'limited', 'value', 'includes', 'standard', 'skills', 'creative']
quality [1, 0, 0, 0, 0, 0, 0, 2, 0, 0]
['likeness', 'disciplines', 'earthly', 'figment', 'untold', 'multitudes', 'motives', 'transgression', 'shyness', 'limitation']
multitude [0, 0, 0, 0, 0, 0, 0, 0, 0]
['vocal', 'digital', 'marketing', 'creative', 'branding', 'storytelling', 'photoshop', 'master', 'html', 'audio']
visual [0, 0, 0, 0, 0, 0, 0, 0, 0, 3]
['

In [38]:
print(adj_wordnet_freq_dict)

{'act': [0, 0, 1, 0, 0, 4, 0, 0, 0, 1], 'cheasy': [], 'small': [0, 0, 0, 0, 0, 2, 2, 3, 0, 0], 'raw': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'compact': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'quality': [1, 0, 0, 0, 0, 0, 0, 2, 0, 0], 'multitude': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'visual': [0, 0, 0, 0, 0, 0, 0, 0, 0, 3], 'loud': [0, 0, 0, 0, 2, 0, 1, 1, 2, 0], 'real': [56, 2, 0, 21, 4, 1, 0, 0, 0, 0], 'tried': [2, 1, 0, 0, 1, 0, 0, 0, 0, 0], 'old': [2, 1, 0, 1, 8, 0, 0, 0, 1, 0], 'sharp': [0, 1, 0, 0, 1, 0, 0, 2, 0, 0], 'christmas': [0, 0, 0, 5, 0, 0, 0, 1, 0, 0], 'older': [0, 0, 0, 0, 21, 0, 0, 0, 3, 1], 'noiseless': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'quick': [5, 21, 0, 4, 0, 2, 3, 0, 2, 0], 'flimsy': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'negative': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'installed': [0, 0, 0, 0, 0, 0, 0, 2, 0, 0], 'present': [0, 0, 0, 7, 0, 0, 0, 0, 1, 0], 'regular': [2, 0, 1, 0, 0, 0, 0, 0, 0, 0], 'silent': [3, 0, 0, 0, 0, 0, 0, 2, 0, 0], 'video': [0, 0, 0, 0, 0, 0, 0, 0, 4, 9], 'remote': [0, 0, 0,

In [39]:
len(adj_wordnet_freq_dict)

152

In [40]:
print(Vri)

[[0, 0, 1, 0, 0, 4, 0, 0, 0, 1], [], [0, 0, 0, 0, 0, 2, 2, 3, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 2, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 3], [0, 0, 0, 0, 2, 0, 1, 1, 2, 0], [56, 2, 0, 21, 4, 1, 0, 0, 0, 0], [2, 1, 0, 0, 1, 0, 0, 0, 0, 0], [2, 1, 0, 1, 8, 0, 0, 0, 1, 0], [0, 1, 0, 0, 1, 0, 0, 2, 0, 0], [0, 0, 0, 5, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 21, 0, 0, 0, 3, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [5, 21, 0, 4, 0, 2, 3, 0, 2, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 2, 0, 0], [0, 0, 0, 7, 0, 0, 0, 0, 1, 0], [2, 0, 1, 0, 0, 0, 0, 0, 0, 0], [3, 0, 0, 0, 0, 0, 0, 2, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 4, 9], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 4, 0, 0, 0, 0, 7, 0, 0, 0], [0, 1, 12, 0, 0, 0, 0, 5, 0, 0], [0, 0, 1, 1, 0, 0, 2, 1, 0, 0], [0, 8, 0, 0, 0, 0, 0, 2, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 1, 0], [0, 

In [41]:
len(Vri)

152

In [43]:
#Step 3: Computing for each implicit aspect in y , the vector containing frequency of all adjectives of that aspect  

In [42]:
#retreiving only unique aspects from y

In [44]:
y_unique=list(set(y))

In [45]:
print(y_unique)

['size', 'functionality', 'behavior', 'appearance', 'quality', 'price', 'weight', 'performance']


In [46]:
len(y_unique)

8

In [47]:
print(len(X_list), len(y_list))

163 163


In [48]:
#Extracting and counting the frequency of all adjectives related to each aspect in y_unique and storing it in a vector
all_aspects_adjectives=[]    #Creating an empty list to store all the adjectives related to all aspects with duplicates
aspect_adjectives_dict={}    #Creating a dictionary to store all aspects and their corresponding unique adjectives in a key value pair form
Vaj=[]                       #Creating a Vaj list to store frequencies of all the unique adjective for each aspect in a sublist
aspect_adj_freq_dict={}      #Creating a dictionary to store the aspect and its related adjectives frequency vector

#we are trying to extract aspect based adjectives
for aspect1 in y_unique:
    aspect_adjectives=[]
    for i in range(len(X_list)):
        if aspect1==dataset.loc[i,'Implicit Aspect']:
            tokenized_sentence=nltk.word_tokenize(X_list[i])
            #Removing stopwords and non-alphabetic characters from tokenized_sentence
            words = [word for word in tokenized_sentence if word.isalpha() and word not in stop_words]   #words is a list that contains all the tokenized words excluding non-alphabetic and stopwords of a sentence
            # Lemmatize the words
            words = [lemmatizer.lemmatize(word) for word in words]    #converting all the tokenized words into their root form
            for word, pos in nltk.pos_tag(words):  #nltk.pos_tag(sentence) is used to tag the parts of speech of words in a sentence and returns a list of tuples, where each tuple contains the word and its corresponding part of speech tag.
                #The for loop is used to iterate through each tuple in the list returned by pos_tag().The loop assigns the first element of each tuple (the word) to the variable word, and the second element (the part of speech tag) to the variable pos.
                if pos.startswith('JJ'):
                    aspect_adjectives.append(word.lower())  #storing all the adjectives including duplicates for an aspect in the list aspect_adjectives
                    all_aspects_adjectives.append(word)  #storing all the extracted adjectives including duplicates for each aspects in a single list 
    
    #Selecting only the unique adjectives from the list containing duplicate adjectives for the above aspect
    aspect_adjectives_unique=list(set(aspect_adjectives))
    
    #Appending the dictionary with aspect term and its related adjectives in a key value form
    aspect_adjectives_dict.update({aspect1:aspect_adjectives_unique}) 
    
    # Compute frequency vector for each aspect adjectives
    fti = [new_corpus_words.count(adjective) for adjective in aspect_adjectives_unique]   #creates a list called fti using a list comprehension.
    
    #Appending Vaj vector with frequencies of all adjectives related to each aspect stored in a sublist
    Vaj.append(fti)
    
    #Similarly appending a dictionary aspect_adj_freq_dict to store all the aspects and their corresponding list of frequencies of all adjectives in a key-value pair form
    aspect_adj_freq_dict.update({aspect1:fti})

In [49]:
print(Vaj)

[[2, 2, 12, 4, 4, 2, 3, 2, 5, 3, 3, 5, 5, 3, 3, 5], [1, 7, 1, 3, 1, 2, 4, 1, 1, 3, 1, 2, 3, 2, 4, 22, 2, 1, 5, 4, 1], [1, 2, 2, 4, 1, 4, 17, 9, 2, 2, 1], [12, 4, 1, 3, 5, 5, 1, 3, 1, 1, 5, 7, 1, 3, 1, 3, 2, 1, 57, 5, 3, 1], [12, 3, 2, 7, 1, 18, 3, 5, 1, 1, 2, 10, 1, 2, 9, 1, 1, 3, 1, 1, 1, 1, 7, 2, 6, 3, 4, 7, 1, 1, 2, 2, 1, 4, 4, 3, 1, 57, 1, 1, 1, 1], [8, 1, 12, 4, 1, 2, 4, 1, 1, 2, 1, 2, 3], [5, 2, 4, 5], [5, 6, 4, 12, 7, 1, 17, 3, 2, 1, 2, 1, 1, 1, 2, 2, 10, 1, 4, 2, 4, 1, 9, 1, 1, 1, 4, 1, 3, 1, 1, 2, 2, 1, 3, 1, 2, 4, 2, 7, 1, 6, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 4, 1, 1, 1, 4, 2, 2, 1, 2, 22, 9, 57, 3, 1, 4, 1, 8]]


In [50]:
len(Vaj)

8

In [51]:
print(aspect_adj_freq_dict)

{'size': [2, 2, 12, 4, 4, 2, 3, 2, 5, 3, 3, 5, 5, 3, 3, 5], 'functionality': [1, 7, 1, 3, 1, 2, 4, 1, 1, 3, 1, 2, 3, 2, 4, 22, 2, 1, 5, 4, 1], 'behavior': [1, 2, 2, 4, 1, 4, 17, 9, 2, 2, 1], 'appearance': [12, 4, 1, 3, 5, 5, 1, 3, 1, 1, 5, 7, 1, 3, 1, 3, 2, 1, 57, 5, 3, 1], 'quality': [12, 3, 2, 7, 1, 18, 3, 5, 1, 1, 2, 10, 1, 2, 9, 1, 1, 3, 1, 1, 1, 1, 7, 2, 6, 3, 4, 7, 1, 1, 2, 2, 1, 4, 4, 3, 1, 57, 1, 1, 1, 1], 'price': [8, 1, 12, 4, 1, 2, 4, 1, 1, 2, 1, 2, 3], 'weight': [5, 2, 4, 5], 'performance': [5, 6, 4, 12, 7, 1, 17, 3, 2, 1, 2, 1, 1, 1, 2, 2, 10, 1, 4, 2, 4, 1, 9, 1, 1, 1, 4, 1, 3, 1, 1, 2, 2, 1, 3, 1, 2, 4, 2, 7, 1, 6, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 4, 1, 1, 1, 4, 2, 2, 1, 2, 22, 9, 57, 3, 1, 4, 1, 8]}


In [52]:
len(aspect_adj_freq_dict)

8

In [53]:
print(aspect_adjectives_dict)

{'size': ['mirrorlike', 'oppressed', 'good', 'lightweight', 'small', 'affordable', 'compact', 'portable', 'slim', 'front', 'cool', 'easy', 'light', 'attractive', 'much', 'sure'], 'functionality': ['nicer', 'several', 'recent', 'compact', 'multitude', 'stack', 'new', 'main', 'signal', 'video', 'connect', 'smart', 'attractive', 'surprised', 'able', 'disc', 'gb', 'many', 'easy', 'different', 'allow'], 'behavior': ['silent', 'big', 'loud', 'lightweight', 'quality', 'old', 'read', 'fine', 'standard', 'best', 'stable'], 'appearance': ['good', 'small', 'ok', 'compact', 'sleek', 'sure', 'real', 'little', 'loaded', 'overlook', 'slim', 'great', 'willing', 'front', 'funny', 'attractive', 'mirrorlike', 'shiny', 'dvd', 'easy', 'cool', 'finest'], 'quality': ['good', 'find', 'cheasy', 'several', 'install', 'nt', 'last', 'sleek', 'nemo', 'february', 'wrong', 'tried', 'entire', 'le', 'fine', 'worth', 'bad', 'little', 'flimsy', 'negative', 'whole', 'installed', 'worked', 'present', 'disk', 'second', 'di

In [54]:
print(len(X))
print(len(y)) 

163
163


In [55]:
#We need to create a Ma(Na,NA) matrix to store the adjective frequency related to each unique aspect 
#Na is the total no.of unique adjectives
#where NA is total number of aspects (also total no. of reviews)

import numpy as np   
Na=len(corpus_adjectives_unique)
NA=len(y)
# create an empty matrix to store the adjective frequency
Ma = np.zeros((Na, NA))

for i, adj in enumerate(corpus_adjectives_unique):    #selecting an adjective from the list of corpus_adjective_unique
    for j, asp in enumerate(y): 
        asp_value_list=aspect_adjectives_dict[asp]   #will give the list of all adjectives(unique) related to asp
        for value_adj in asp_value_list:
            if adj==value_adj:
                index_adj=asp_value_list.index(adj)
                Ma[i,j]=aspect_adj_freq_dict[asp][index_adj]

In [56]:
len(corpus_adjectives_unique)

152

In [57]:
print(Ma)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 4. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [8. 8. 0. ... 8. 8. 8.]]


In [58]:
print(Ma.shape)

(152, 163)


In [59]:
#Step4: Computing the global frequency vector for each adjective a(i) (from the list corpus_adjectives_unique) and all its WN related words as follows:
#Vrg(i)=ft(i)*Vri(i)

In [60]:
#Counting for each adjective in corpus_adjectives_unique its frequency in new_corpus_words and storing the pair in a dictionary
adj_freq_dict={}
for adj in corpus_adjectives_unique:
    freq_adj=new_corpus_words.count(adj)
    adj_freq_dict.update({adj:freq_adj})

In [61]:
print(adj_freq_dict)

{'act': 1, 'cheasy': 2, 'small': 4, 'raw': 1, 'compact': 3, 'quality': 1, 'multitude': 1, 'visual': 1, 'loud': 2, 'real': 1, 'tried': 10, 'old': 4, 'sharp': 1, 'christmas': 4, 'older': 1, 'noiseless': 2, 'quick': 1, 'flimsy': 1, 'negative': 1, 'installed': 1, 'present': 2, 'regular': 1, 'silent': 1, 'video': 3, 'remote': 4, 'certain': 2, 'great': 7, 'worse': 1, 'file': 5, 'front': 3, 'progressive': 1, 'attractive': 3, 'disposable': 1, 'claim': 2, 'oppressed': 2, 'couple': 1, 'uk': 1, 'longterm': 1, 'bang': 1, 'wma': 2, 'smooth': 1, 'many': 1, 'dvd': 57, 'crappy': 1, 'inexpensive': 2, 'allow': 1, 'poor': 1, 'tv': 4, 'several': 7, 'audio': 3, 'backup': 2, 'attempted': 1, 'froze': 1, 'cheep': 1, 'wide': 1, 'affordable': 2, 'broken': 1, 'whole': 1, 'kodak': 2, 'main': 1, 'disk': 6, 'rental': 1, 'fit': 4, 'portable': 2, 'slim': 5, 'best': 2, 'light': 5, 'smart': 2, 'scan': 1, 'occasional': 1, 'surprised': 2, 'mirrorlike': 2, 'expensive': 1, 'drawer': 1, 'looked': 4, 'pirate': 1, 'disc': 22,

In [62]:
len(adj_freq_dict)

152

In [63]:
#Now since we have to two separate dictionaries one adj_freq_dict storing the frequency of each adjective
#and the other one is adj_wordnet_freq_dict storing for each adjective its wordnet related words frequency

In [64]:
print(adj_wordnet_freq_dict)

{'act': [0, 0, 1, 0, 0, 4, 0, 0, 0, 1], 'cheasy': [], 'small': [0, 0, 0, 0, 0, 2, 2, 3, 0, 0], 'raw': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'compact': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'quality': [1, 0, 0, 0, 0, 0, 0, 2, 0, 0], 'multitude': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'visual': [0, 0, 0, 0, 0, 0, 0, 0, 0, 3], 'loud': [0, 0, 0, 0, 2, 0, 1, 1, 2, 0], 'real': [56, 2, 0, 21, 4, 1, 0, 0, 0, 0], 'tried': [2, 1, 0, 0, 1, 0, 0, 0, 0, 0], 'old': [2, 1, 0, 1, 8, 0, 0, 0, 1, 0], 'sharp': [0, 1, 0, 0, 1, 0, 0, 2, 0, 0], 'christmas': [0, 0, 0, 5, 0, 0, 0, 1, 0, 0], 'older': [0, 0, 0, 0, 21, 0, 0, 0, 3, 1], 'noiseless': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'quick': [5, 21, 0, 4, 0, 2, 3, 0, 2, 0], 'flimsy': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'negative': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'installed': [0, 0, 0, 0, 0, 0, 0, 2, 0, 0], 'present': [0, 0, 0, 7, 0, 0, 0, 0, 1, 0], 'regular': [2, 0, 1, 0, 0, 0, 0, 0, 0, 0], 'silent': [3, 0, 0, 0, 0, 0, 0, 2, 0, 0], 'video': [0, 0, 0, 0, 0, 0, 0, 0, 4, 9], 'remote': [0, 0, 0,

In [65]:
#Now we have to multiply the frequency of adjectives with each term contained in its Wordnet frequency vector
Vrg=[]                   #creating a list to store the global frequency of all adjectives in a sublist
global_freq_adj_dict={}  #creating a dictionary to store all the adjectives and their corresponding global frequency vector
for adj1 in adj_freq_dict:   
    for adj2 in adj_wordnet_freq_dict:
        if adj1==adj2:
            global_freq_adj=[]        #creating a list to store the global freq vector of an adjective
            freq_adj1=adj_freq_dict[adj1]   #retreiving the frequency of adj1 from adj_freq_dict
            adj2_wordnet_freq_list=adj_wordnet_freq_dict[adj2]   #retrieving the wordnet freq vector of adj2 where adj1=adj2
            for wn_freq in adj2_wordnet_freq_list:
                product=freq_adj1*wn_freq
                global_freq_adj.append(product)
            Vrg.append(global_freq_adj)
            global_freq_adj_dict.update({adj1:global_freq_adj})

In [66]:
print(Vrg)

[[0, 0, 1, 0, 0, 4, 0, 0, 0, 1], [], [0, 0, 0, 0, 0, 8, 8, 12, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 2, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 3], [0, 0, 0, 0, 4, 0, 2, 2, 4, 0], [56, 2, 0, 21, 4, 1, 0, 0, 0, 0], [20, 10, 0, 0, 10, 0, 0, 0, 0, 0], [8, 4, 0, 4, 32, 0, 0, 0, 4, 0], [0, 1, 0, 0, 1, 0, 0, 2, 0, 0], [0, 0, 0, 20, 0, 0, 0, 4, 0, 0], [0, 0, 0, 0, 21, 0, 0, 0, 3, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [5, 21, 0, 4, 0, 2, 3, 0, 2, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 2, 0, 0], [0, 0, 0, 14, 0, 0, 0, 0, 2, 0], [2, 0, 1, 0, 0, 0, 0, 0, 0, 0], [3, 0, 0, 0, 0, 0, 0, 2, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 12, 27], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 8, 0, 0, 0, 0, 14, 0, 0, 0], [0, 7, 84, 0, 0, 0, 0, 35, 0, 0], [0, 0, 1, 1, 0, 0, 2, 1, 0, 0], [0, 40, 0, 0, 0, 0, 0, 10, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 3, 0

In [67]:
print(global_freq_adj_dict)

{'act': [0, 0, 1, 0, 0, 4, 0, 0, 0, 1], 'cheasy': [], 'small': [0, 0, 0, 0, 0, 8, 8, 12, 0, 0], 'raw': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'compact': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'quality': [1, 0, 0, 0, 0, 0, 0, 2, 0, 0], 'multitude': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'visual': [0, 0, 0, 0, 0, 0, 0, 0, 0, 3], 'loud': [0, 0, 0, 0, 4, 0, 2, 2, 4, 0], 'real': [56, 2, 0, 21, 4, 1, 0, 0, 0, 0], 'tried': [20, 10, 0, 0, 10, 0, 0, 0, 0, 0], 'old': [8, 4, 0, 4, 32, 0, 0, 0, 4, 0], 'sharp': [0, 1, 0, 0, 1, 0, 0, 2, 0, 0], 'christmas': [0, 0, 0, 20, 0, 0, 0, 4, 0, 0], 'older': [0, 0, 0, 0, 21, 0, 0, 0, 3, 1], 'noiseless': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'quick': [5, 21, 0, 4, 0, 2, 3, 0, 2, 0], 'flimsy': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'negative': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'installed': [0, 0, 0, 0, 0, 0, 0, 2, 0, 0], 'present': [0, 0, 0, 14, 0, 0, 0, 0, 2, 0], 'regular': [2, 0, 1, 0, 0, 0, 0, 0, 0, 0], 'silent': [3, 0, 0, 0, 0, 0, 0, 2, 0, 0], 'video': [0, 0, 0, 0, 0, 0, 0, 0, 12, 27], 'remote': 

In [68]:
#Step5: Computing aspect global frequency vector for each aspect j and all its WN related words (related WN words of all adjectives in aspect j)
#and updating a matrix Mr(Nr,NA) where Nr is the list of all unique wordnet related terms of all aspects related adjectives

In [69]:
#we know that all the wordnets related to all the adjectives are stored in all_wordnets list
#But we need is the list of unique wordnets of all the adjectives

all_wordnets_unique=list(set(all_wordnets))

In [70]:
print(all_wordnets_unique)

['though', 'lui', 'redstone', 'theme', 'basic', 'stupid', 'economics', 'act', 'september', 'impossible', 'multiple', 'document', 'pack', 'funimation', 'shadow', 'bargain', 'pious', 'proper', 'service', 'philosophy', 'old', 'shaper', 'news', 'cover', 'down', 'glittery', 'sink', 'shyness', 'girl', 'possibly', 'booklet', 'rubbish', 'guess', 'perfect', 'dory', 'video', 'price', 'funky', 'ugly', 'option', 'both', 'claiming', 'computer', 'flex', 'warrant', 'board', 'entrepreneurial', 'eye', 'emotion', 'goalless', 'login', 'sony', 'or', 'create', ':o', 'today', 'sentenced', 'many', 'impoverished', 'accused', 'album', 'beat', 'shelf', 'fold', 'puked', 'allow', 'narnia', 'determined', 'charged', 'eco-friendly', 'ラウンドファスナー', 'ppl', 'hdtv', 'look', 'decided', 'io', 'high', 'pureview', 'swedish', 'compartment', 'called', 'audio', 'cost-effective', 'calculating', 'ball', 'stylish', 'january', 'xm', 'n’t', 'engine', 'tear', 'curling', 'acrylic', 'magic', 'wide', 'unrecognisable', 'scratched', 'felt'

In [71]:
len(all_wordnets)

1473

In [72]:
len(all_wordnets_unique)

1085

In [73]:
Nr=len(all_wordnets_unique)

In [74]:
print(adj_wordnets_dict)

{'act': ['talk', 'understand', 'speak', 'ppl', 'stand', 'lie', 'not', 'person', 'honest', 'people'], 'cheasy': [], 'small': ['their', 'more', 'clean', 'find', 'your', 'own', 'or', 'looking', 'side', 'bigger'], 'raw': ['epic', 'bowl', 'magic', 'wing', 'ultimate', 'spanish', 'horse', 'classic', 'dutch', 'wild'], 'compact': ['analog', 'inch', 'optical', 'laser', 'infrared', 'lens', 'aluminum', 'magenta', 'tripod', 'pvc'], 'quality': ['brand', 'creative', 'selection', 'value', 'includes', 'professional', 'product', 'standard', 'limited', 'skill'], 'multitude': ['transgression', 'discipline', 'likeness', 'shyness', 'limitation', 'motif', 'earthly', 'figment', 'untold'], 'visual': ['creative', 'marketing', 'html', 'master', 'audio', 'storytelling', 'photoshop', 'digital', 'branding', 'vocal'], 'loud': ['scary', 'sound', 'mess', 'lonely', 'blowing', 'turn', 'noise', 'crazy', 'scared', 'drunk'], 'real': ['big', 'beat', 'stand', 'young', 'better', 'than', 'one', 'bad', 'play', 'crazy'], 'tried'

In [75]:
for adj in adj_wordnets_dict:
    list=adj_wordnets_dict[adj]
    print(adj,'-->',list)

act --> ['talk', 'understand', 'speak', 'ppl', 'stand', 'lie', 'not', 'person', 'honest', 'people']
cheasy --> []
small --> ['their', 'more', 'clean', 'find', 'your', 'own', 'or', 'looking', 'side', 'bigger']
raw --> ['epic', 'bowl', 'magic', 'wing', 'ultimate', 'spanish', 'horse', 'classic', 'dutch', 'wild']
compact --> ['analog', 'inch', 'optical', 'laser', 'infrared', 'lens', 'aluminum', 'magenta', 'tripod', 'pvc']
quality --> ['brand', 'creative', 'selection', 'value', 'includes', 'professional', 'product', 'standard', 'limited', 'skill']
multitude --> ['transgression', 'discipline', 'likeness', 'shyness', 'limitation', 'motif', 'earthly', 'figment', 'untold']
visual --> ['creative', 'marketing', 'html', 'master', 'audio', 'storytelling', 'photoshop', 'digital', 'branding', 'vocal']
loud --> ['scary', 'sound', 'mess', 'lonely', 'blowing', 'turn', 'noise', 'crazy', 'scared', 'drunk']
real --> ['big', 'beat', 'stand', 'young', 'better', 'than', 'one', 'bad', 'play', 'crazy']
tried --

In [76]:
# Creating an empty matrix to store the WN frequency for each aspect
Mr = np.zeros((Nr, NA))

#Nr is the total no. of unique wordnets
#NA is the total no. of aspects


for i, wordnet in enumerate(all_wordnets_unique):
    for j, aspect in enumerate(y):
        asp_adj_list=aspect_adjectives_dict[aspect]  #retreiving the list of adjectives related to the aspect
        for adj in asp_adj_list:      #iterating through each adjective in the list
            if adj in adj_wordnets_dict:
                adj_wn_list=adj_wordnets_dict[adj]
                for wn in adj_wn_list:
                    if wordnet==wn:
                        wn_freq=new_corpus_words.count(wn)
                        adj_freq=adj_freq_dict[adj]
                        aspect_wordnet_freq=wn_freq*adj_freq
                        Mr[i,j]=aspect_wordnet_freq

In [77]:
print(Mr)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [78]:
#Step6: Augmenting the two matrices Ma and Mr vertically called stacking

# Augment the matrices vertically
Mt = np.vstack((Ma, Mr))

In [79]:
print(Mt)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 4. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [80]:
#Phase 2: NB training

In [81]:
Mt_transpose=Mt.transpose()

In [82]:
print(Mt_transpose)   #Mt_transpose contains list of all aspects in rows and list of all adjectives + WN related words in column

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 4. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [83]:
print(Mt_transpose.shape)

(163, 1237)


In [84]:
print(len(y))

163


In [85]:
type(y)

numpy.ndarray

In [89]:
from sklearn.model_selection import KFold

# Initialize a Multinomial Naive Bayes classifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

# Initialize a Multinomial Naive Bayes classifier
clf = MultinomialNB()

# define the number of folds for cross-validation
num_folds = 5

# create a KFold object to split the data into folds
kf = KFold(n_splits=num_folds)

In [90]:
f1_micro=[]
f1_macro=[]
precision_micro_list=[]
precision_macro_list=[]
recall_micro_list=[]
recall_macro_list=[]

# iterate over each fold
for train_index, test_index in kf.split(Mt_transpose):

    # get the training and testing data for this fold
    X_train, X_test = Mt_transpose[train_index], Mt_transpose[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # train the classifier on the training data
    clf.fit(X_train, y_train)

    # make predictions on the testing data
    y_pred = clf.predict(X_test)
      
    print(np.concatenate((y_test.reshape(len(y_test),1),y_pred.reshape(len(y_pred),1)),1))
   

    #calculate the accuracy of the classifier on the testing data for this fold
    accuracy = accuracy_score(y_test, y_pred)
    print("Accuracy:", accuracy)
    
    print()
   
    #calculate the precision(micro) of the classifier on the testing data for this fold
    precision_micro= precision_score(y_test,y_pred, average='micro',zero_division=1)
    print('precision score(micro):',precision_micro)
    precision_micro_list.append(precision_micro)
      
    #calculate the precision(macro) of the classifier on the testing data for this fold
    precision_macro= precision_score(y_test,y_pred, average='macro',zero_division=1)
    print('precision score(macro):',precision_macro)
    precision_macro_list.append(precision_macro)
    
    print()
    
    #calculate the recall(micro) of the classifier on the testing data for this fold
    recall_micro=recall_score(y_test,y_pred, average='micro')
    print('recall score(micro):',recall_micro)
    recall_micro_list.append(recall_micro)
    
    #calculate the recall(macro) of the classifier on the testing data for this fold
    recall_macro=recall_score(y_test,y_pred, average='macro')
    print('recall score(macro):',recall_macro)
    recall_macro_list.append(recall_macro)
    
    print() 
    
    # calculate the F1 score for your predictions
    f1 = f1_score(y_test, y_pred, average='micro')
    print("F1 score(micro):", f1)
    f1_micro.append(f1)
    
    # calculate the F1 score for your predictions
    f1 = f1_score(y_test, y_pred, average='macro')
    print("F1 score(macro):", f1)
    f1_macro.append(f1)
 
    print()
    print()    

[['performance' 'performance']
 ['performance' 'performance']
 ['appearance' 'appearance']
 ['functionality' 'functionality']
 ['performance' 'performance']
 ['appearance' 'appearance']
 ['quality' 'quality']
 ['performance' 'performance']
 ['quality' 'quality']
 ['appearance' 'appearance']
 ['quality' 'quality']
 ['performance' 'performance']
 ['functionality' 'functionality']
 ['performance' 'performance']
 ['functionality' 'functionality']
 ['functionality' 'functionality']
 ['performance' 'performance']
 ['performance' 'performance']
 ['performance' 'performance']
 ['quality' 'quality']
 ['quality' 'quality']
 ['quality' 'quality']
 ['performance' 'performance']
 ['performance' 'performance']
 ['quality' 'quality']
 ['performance' 'performance']
 ['functionality' 'functionality']
 ['functionality' 'functionality']
 ['quality' 'quality']
 ['quality' 'quality']
 ['performance' 'performance']
 ['functionality' 'functionality']
 ['performance' 'performance']]
Accuracy: 1.0

precision s

In [91]:
precision_micro_sum=sum(precision_micro_list)
precision_micro_len=len(precision_micro_list)
precision_micro_avg=precision_micro_sum/precision_micro_len
print('precision_score(micro):',precision_micro_avg)

precision_macro_sum=sum(precision_macro_list)
precision_macro_len=len(precision_macro_list)
precision_macro_avg=precision_macro_sum/precision_macro_len
print('precision_score(macro):',precision_macro_avg)

print()

recall_micro_sum=sum(recall_micro_list)
recall_micro_len=len(recall_micro_list)
recall_micro_avg=recall_micro_sum/recall_micro_len
print('recall_score(micro):',recall_micro_avg)

recall_macro_sum=sum(recall_macro_list)
recall_macro_len=len(recall_macro_list)
recall_macro_avg=recall_macro_sum/recall_macro_len
print('recall_score(macro):',recall_macro_avg)

print()

f1_micro_sum=sum(f1_micro)
f1_micro_len=len(f1_micro)
f1_micro_avg=f1_micro_sum/f1_micro_len
print('f1_score(micro):',f1_micro_avg)

f1_macro_sum=sum(f1_macro)
f1_macro_len=len(f1_macro)
f1_macro_avg=f1_macro_sum/f1_macro_len
print('f1_score(macro):',f1_macro_avg)

precision_score(micro): 0.9875
precision_score(macro): 0.9833333333333334

recall_score(micro): 0.9875
recall_score(macro): 0.975

f1_score(micro): 0.9875
f1_score(macro): 0.9625
